### ISSUE TITLE
Holes in a contour

### ISSUE THREAD

**Issue by thomaskilian** [lycantropos/sect#9]
Hi, I'm trying to figure out, how to pass holes with the contours. The constrained_delaunay seems to be able to deal with that but from the documentation I could not find out how.

**Comment by lycantropos** [comment]
Hi @thomaskilian, to pass a contour with holes (which themselves are also contours) -- just construct a `Polygon`, its constructor accepts border with holes.
This is [an example](https://github.com/lycantropos/sect/blob/e362cd9518def706822e785e1aa56509605ce567/README.md?plain=1#L90-L101).

Hope this helps.

**Comment by thomaskilian** [comment]
Hi @lycantropos Thanks for the quick feedback. Unfortunately that will raise an error. I tried a small square inside a square:
`x =  Triangulation.constrained_delaunay(
          Polygon(Contour([Point(0, 0), Point(4, 0), Point(4, 4), Point(0, 4), Point(0, 0)]),
                  [Contour([Point(1, 1), Point(1, 2), Point(2, 2), Point(2, 1), Point(1, 1)])]),
          context=context
      ).triangles()
`
and it croaks like

> File "/Users/thomaskilian/Downloads/tri.py", line 8, in <module>
>   x = Triangulation.constrained_delaunay(
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sect/core/delaunay/triangulation.py", line 116, in constrained_delaunay
>   cut(result, holes)
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sect/core/delaunay/triangulation.py", line 279, in cut
>   for event in events_queue.sweep():
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sect/core/delaunay/events_queue.py", line 170, in sweep
>   and self.detect_intersection(event, above_event)):
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sect/core/delaunay/events_queue.py", line 94, in detect_intersection
>   raise ValueError('Edges of the same polygon '

**Comment by lycantropos** [comment]
@thomaskilian : it's because your first vertex and the last vertex are equal, when they shouldn't (since it's redundant), try
```python
x =  Triangulation.constrained_delaunay( Polygon(Contour([Point(0, 0), Point(4, 0), Point(4, 4), Point(0, 4)]), [Contour([Point(1, 1), Point(1, 2), Point(2, 2), Point(2, 1)])]), context=context ).triangles()
```
instead

**Comment by thomaskilian** [comment]
Well, that definitely looks better :-) The geo-libs usually provide ring objects witth first and last point the same (redundance I found strange) so I adopted that. Thanks again!

**Comment by thomaskilian** [comment]
Sorry to bother you once more. But how would I pass a figure like this: 
<img width="218" alt="Bildschirmfoto 2023-12-20 um 18 53 57" src="https://github.com/lycantropos/sect/assets/69296/8febacb4-c285-4f68-926b-09f34a52110c">
It does not see the dent top left and returns
<img width="253" alt="Bildschirmfoto 2023-12-20 um 19 06 24" 
src="https://github.com/lycantropos/sect/assets/69296/a32b2dc7-8045-4380-966a-07785be00a39">

I assume that I have to specifx that area as hole, right? Or is there an easier way?

**Comment by lycantropos** [comment]
like that
```python
from ground.base import get_context

context = get_context()
Polygon = context.polygon_cls
Point = context.point_cls
Contour = context.contour_cls
assert Triangulation.constrained_delaunay(
        Polygon(Contour([Point(0, 0), Point(3, 0), Point(3, 3), Point(1, 3),
                         Point(1, 2), Point(0, 2)]), []),
        context=context
).triangles() == [
           Contour([Point(1, 2), Point(3, 0), Point(3, 3)]),
           Contour([Point(0, 0), Point(3, 0), Point(1, 2)]),
           Contour([Point(1, 2), Point(3, 3), Point(1, 3)]),
           Contour([Point(0, 0), Point(1, 2), Point(0, 2)])
       ]
```
?

**Comment by thomaskilian** [comment]
WOW! You made someone very happy! :-)
